version: '3.7'

services:
  app:
    image: $IMAGE
    volumes:
      - $PERSISTENT_DATA:/app/data/:rw
    deploy:
      mode: global
      restart_policy:
        condition: none
      update_config:
        order: stop-first
        failure_action: continue
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
    secrets:
      - source: versions_register_config
        target: /app/.env
    entrypoint: /app/entrypoint.sh
     
secrets:
  versions_register_config:
    name: versions_register_config
    external: true